# Generated by Django 5.2.8 on 2026-01-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.TextField(blank=True, help_text='Answer for text questions', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.JSONField(blank=True, help_text="Keywords for grading text answers e.g. ['pythagoras', 'triangle']", null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, help_text='Correct option key e.g. A', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text="MCQ options e.g. {A: 'Option1', B: 'Option2'}", null=True),
        ),
    ]
