# Generated by Django 5.2.8 on 2026-01-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_question_correct_text_answer_question_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TEXT', 'Text Answer')], default='MCQ', max_length=10),
        ),
    ]
